-- Written by the publish tools' addon catalog script from its addon list, the
-- addons' TOCs and the approved showcase images. Do not edit by hand: change the
-- inputs and run the script again.
--
-- CobySuite.UI.AddonCatalog: every released addon, in list order. Images live in
-- Media\Showcase\<folder>\<file>: w and h are the picture's size in pixels on a
-- cw x ch canvas (crop with SetTexCoord(0, w / cw, 0, h / ch)). thumb is the same
-- picture shrunk for the list's small tiles, described the same way.
CobySuite_CobysCrestExchange.UI.AddonCatalog = {
  {
    folder = "Recollect", title = "Recollect",
    icon = "Interface\\Icons\\achievement_faction_goldenlotus",
    slash = "/recollect", url = "https://www.curseforge.com/wow/addons/recollect",
    blurb = "Hover any item to see what it is for and whether you still need it, across your bags, bank and warband bank.",
    images = {
      { file = "01.png", w = 562, h = 260, cw = 1024, ch = 512,
        thumb = { file = "01-thumb.png", w = 248, h = 115, cw = 256, ch = 128 },
        caption = "Hover any item: Recollect says what it's for and whether you still need it." },
      { file = "02.png", w = 1024, h = 595, cw = 1024, ch = 1024,
        thumb = { file = "02-thumb.png", w = 248, h = 144, cw = 256, ch = 256 },
        caption = "Review items across your bags, bank and warband bank, with verdicts and reasons." },
      { file = "03.png", w = 869, h = 699, cw = 1024, ch = 1024,
        thumb = { file = "03-thumb.png", w = 209, h = 168, cw = 256, ch = 256 },
        caption = "Everything about an item in one window: what it's for, what it counts toward, the recipes that use it and what you hold." },
      { file = "04.png", w = 869, h = 699, cw = 1024, ch = 1024,
        thumb = { file = "04-thumb.png", w = 209, h = 168, cw = 256, ch = 256 },
        caption = "See what a currency item buys, and what you still need to collect." },
    },
  },
  {
    folder = "CobysLinkepedia", title = "Coby's Linkepedia",
    icon = "Interface\\Icons\\INV_Misc_Book_09",
    slash = "/lp", url = "https://www.curseforge.com/wow/addons/linkepedia",
    blurb = "Search, autocomplete and link any item in the game, from a database your own client builds.",
    images = {
      { file = "01.png", w = 355, h = 255, cw = 512, ch = 256,
        thumb = { file = "01-thumb.png", w = 234, h = 168, cw = 256, ch = 256 },
        caption = "Type [ and an item name. Press Tab to insert its link." },
      { file = "02.png", w = 1021, h = 734, cw = 1024, ch = 1024,
        thumb = { file = "02-thumb.png", w = 234, h = 168, cw = 256, ch = 256 },
        caption = "Find and link items, even ones you don't own." },
      { file = "03.png", w = 1021, h = 734, cw = 1024, ch = 1024,
        thumb = { file = "03-thumb.png", w = 234, h = 168, cw = 256, ch = 256 },
        caption = "Build and save links for specific gear variants." },
      { file = "04.png", w = 1021, h = 830, cw = 1024, ch = 1024,
        thumb = { file = "04-thumb.png", w = 207, h = 168, cw = 256, ch = 256 },
        caption = "See what your item database holds, at a glance." },
    },
  },
  {
    folder = "CobysLootSweeper", title = "Coby's Loot Sweeper",
    icon = "Interface\\Icons\\INV_Misc_Bag_10",
    slash = "/ls", url = "https://www.curseforge.com/wow/addons/cobys-loot-sweeper",
    blurb = "Sell the loot from your old-raid and dungeon runs in one go, and see what is worth auctioning. What you already had stays safe.",
    images = {
      { file = "01.png", w = 857, h = 563, cw = 1024, ch = 1024,
        thumb = { file = "01-thumb.png", w = 248, h = 163, cw = 256, ch = 256 },
        caption = "Your run's loot, sorted for vendoring, auctioning or keeping." },
      { file = "02.png", w = 857, h = 563, cw = 1024, ch = 1024,
        thumb = { file = "02-thumb.png", w = 248, h = 163, cw = 256, ch = 256 },
        caption = "See which loot is worth more at the auction house than at a vendor (sample prices)." },
      { file = "03.png", w = 857, h = 563, cw = 1024, ch = 1024,
        thumb = { file = "03-thumb.png", w = 248, h = 163, cw = 256, ch = 256 },
        caption = "Anything it can't prove came from the run is kept, and it tells you why." },
      { file = "04.png", w = 1024, h = 443, cw = 1024, ch = 512,
        thumb = { file = "04-thumb.png", w = 248, h = 107, cw = 256, ch = 128 },
        caption = "Pick a preset, preview the sale, then sell. Nothing goes until you confirm." },
      { file = "05.png", w = 857, h = 563, cw = 1024, ch = 1024,
        thumb = { file = "05-thumb.png", w = 248, h = 163, cw = 256, ch = 256 },
        caption = "Review what happened to the loot from each run." },
    },
  },
  {
    folder = "CobysCrestExchange", title = "Coby's Crest Exchange",
    icon = "Interface\\Icons\\inv_121_crest_myth",
    slash = "/ce", url = "https://www.curseforge.com/wow/addons/cobys-crest-exchange",
    blurb = "A better crest exchange at Vaskarn: see what you can convert, pick an amount and convert in a few clicks.",
    images = {
      { file = "01.png", w = 546, h = 474, cw = 1024, ch = 512,
        thumb = { file = "01-thumb.png", w = 194, h = 168, cw = 256, ch = 256 },
        caption = "Your whole crest ladder at a glance: balances, caps and the room left under each cap." },
      { file = "02.png", w = 546, h = 474, cw = 1024, ch = 512,
        thumb = { file = "02-thumb.png", w = 194, h = 168, cw = 256, ch = 256 },
        caption = "Type an amount, compare every route, see the path through your lower tiers." },
      { file = "03.png", w = 546, h = 474, cw = 1024, ch = 512,
        thumb = { file = "03-thumb.png", w = 194, h = 168, cw = 256, ch = 256 },
        caption = "One plan across your lower tiers, one confirmation, nothing bought until you say so. Confirm is greyed in this sample." },
      { file = "04.png", w = 546, h = 474, cw = 1024, ch = 512,
        thumb = { file = "04-thumb.png", w = 194, h = 168, cw = 256, ch = 256 },
        caption = "On a character without Hero of the Mist, see the missing requirement and the lowest gear slots." },
    },
  },
  {
    folder = "CobysCurrencySearcher", title = "Coby's Currency Searcher",
    icon = "Interface\\Icons\\INV_Misc_Coin_01",
    slash = "/ccs", url = "https://www.curseforge.com/wow/addons/currency-searcher",
    blurb = "A search box on the Currency tab that finds currencies inside collapsed headers.",
    images = {
      { file = "01.png", w = 400, h = 425, cw = 512, ch = 512,
        thumb = { file = "01-thumb.png", w = 158, h = 168, cw = 256, ch = 256 },
        caption = "Find currencies, even inside collapsed headers." },
      { file = "02.png", w = 400, h = 425, cw = 512, ch = 512,
        thumb = { file = "02-thumb.png", w = 158, h = 168, cw = 256, ch = 256 },
        caption = "Combine filters to find what you need. Shown: Owned + Transferable." },
      { file = "03.png", w = 400, h = 425, cw = 512, ch = 512,
        thumb = { file = "03-thumb.png", w = 158, h = 168, cw = 256, ch = 256 },
        caption = "Keep favorites close. Stars are shared across your characters." },
      { file = "04.png", w = 400, h = 425, cw = 512, ch = 512,
        thumb = { file = "04-thumb.png", w = 158, h = 168, cw = 256, ch = 256 },
        caption = "Switch to a flat list, with each currency's group still visible." },
      { file = "05.png", w = 648, h = 468, cw = 1024, ch = 512,
        thumb = { file = "05-thumb.png", w = 233, h = 168, cw = 256, ch = 256 },
        caption = "Show stars on every row, on search results only, or on hover." },
    },
  },
  {
    folder = "PublicOrderWhisper", title = "Coby's Public Order Whisper",
    icon = "Interface\\Icons\\UI_Chat",
    slash = "/pow", url = "https://www.curseforge.com/wow/addons/public-order-whisper",
    blurb = "A whisper button on public crafting orders that sends your message, with the item link, to the player who placed it.",
    images = {
      { file = "01.png", w = 784, h = 100, cw = 1024, ch = 128,
        thumb = { file = "01-thumb.png", w = 248, h = 32, cw = 256, ch = 32 },
        caption = "A whisper bubble on every public order. One click sends your offer, and green marks who you already whispered." },
      { file = "02.png", w = 656, h = 556, cw = 1024, ch = 1024,
        thumb = { file = "02-thumb.png", w = 198, h = 168, cw = 256, ch = 256 },
        caption = "Write it once. Placeholders fill in the item, name and tip for each order." },
      { file = "03.png", w = 656, h = 556, cw = 1024, ch = 1024,
        thumb = { file = "03-thumb.png", w = 198, h = 168, cw = 256, ch = 256 },
        caption = "Send at once, or open the whisper in your chat box to edit it first. Green marks who you already whispered." },
    },
  },
  {
    folder = "ApexFury", title = "ApexFury",
    icon = "Interface\\Icons\\inv12_apextalent_evoker_risingfury",
    slash = "/af", url = "https://www.curseforge.com/wow/addons/apexfury",
    blurb = "A sound alert at 4 stacks of Rising Fury for Devastation Evokers, so you never miss the window.",
    images = {
      { file = "01.png", w = 753, h = 595, cw = 1024, ch = 1024,
        thumb = { file = "01-thumb.png", w = 213, h = 168, cw = 256, ch = 256 },
        caption = "Choose which Rising Fury stack triggers your sound alert." },
      { file = "02.png", w = 753, h = 595, cw = 1024, ch = 1024,
        thumb = { file = "02-thumb.png", w = 213, h = 168, cw = 256, ch = 256 },
        caption = "Preview and choose your alert sound." },
      { file = "03.png", w = 596, h = 635, cw = 1024, ch = 1024,
        thumb = { file = "03-thumb.png", w = 158, h = 168, cw = 256, ch = 256 },
        caption = "See when alerts play, and what can delay them." },
    },
  },
}
